# Generated by Django 5.2.3 on 2025-06-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendertemplate',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
